# Generated by Django 5.2.7 on 2025-10-11 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('cedula_doctor', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números', regex='^[0-9]+$')])),
                ('nombre_doc', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener números', regex='^[^0-9]+$')])),
                ('especialidad', models.CharField(blank=True, max_length=20, null=True)),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('m', 'Matutino'), ('v', 'Vespertino')], max_length=1)),
                ('telefono_doc', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos', regex='^[0-9]{10}$')])),
                ('correo_doc', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.EmailValidator(message='Ingresa un correo válido')])),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('folio_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener números', regex='^[^0-9]+$')])),
                ('telefono_paciente', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos', regex='^[0-9]{10}$')])),
                ('correo_paciente', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.EmailValidator(message='Ingresa un correo válido')])),
                ('adeudo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('num_cita', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cedula_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.doctor')),
                ('folio_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
            ],
        ),
    ]
