# Generated by Django 5.2.7 on 2025-12-07 01:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='cedula_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='folio_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cedula_doctor',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números', regex='^[0-9]+$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='correo_doc',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.EmailValidator(message='Ingresa un correo válido')], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nombre_doc',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener números', regex='^[^0-9]+$')], verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono_doc',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos', regex='^[0-9]{10}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo_paciente',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.EmailValidator(message='Ingresa un correo válido')], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='folio_paciente',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Fólio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_paciente',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener números', regex='^[^0-9]+$')], verbose_name='Nombre del paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos', regex='^[0-9]{10}$')], verbose_name='Teléfono'),
        ),
    ]
