# Generated by Django 5.2.7 on 2025-12-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_doctor_options_alter_cita_cedula_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCitas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('accion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cedula_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.doctor', verbose_name='Doctor')),
                ('folio_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial de cita',
                'verbose_name_plural': 'Historial de citas',
            },
        ),
    ]
